# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.no.lmdi
canonical: http://hl7.no/fhir/ig/lmdi
name: Lmdi
title: "Legemiddeldata fra institusjon til Legemiddelregisteret"
description: "Denne implementasjongguiden beskriver hvordan institusjoner skal overføre data om legemiddelbruk i institusjoner til Legemiddelregisteret"
status: draft
license: CC-BY-4.0
date: 2025-02-04
language: no
version: 1.0.0

fhirVersion: 4.0.1

copyrightYear: 2024+
releaseLabel: ci-build

publisher:
  name: Folkehelseinstituttet
  url: https://www.fhi.no
contact:
  - name: Legemiddelregisteret
    telecom:
      - system: email
        value: legemiddelregisteret@fhi.no

jurisdiction: urn:iso:std:iso:3166#NO "Norway"

parameters:
  path-assets: input/assets
  apply-contact: true
  apply-jurisdiction: true
  generate-json: true
  generate-xml: false
  generate-turtle: false
# dependencies:
# hl7.fhir.no.basis: 2.1.1
# hl7.fhir.no.basis: 2.2.0


pages:
  index.md:
    title: Hjem
  informasjonsmodell.md:
    title: Informasjonsmodell
  integrasjon.md:
    title: Integrasjon
    SignertKryptertBundle.md:
      title: SignertKryptertBundle
    protokoll.md:
      title: Protokoll
  nedlastinger.md:
    title: Nedlastinger
  profiler.md:
    title: "FHIR-profiler"
    generation: markdown

menu:
  Hjem: index.html
  Informasjonsmodell: informasjonsmodell.html
  Integrasjon: integrasjon.html
  FHIR profiler: profiler.html
  Nedlastinger: nedlastinger.html
 