# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.no.lmdi
canonical: http://hl7.no/fhir/ig/lmdi
name: Lmdi
title: "Legemiddeldata fra institusjon til Legemiddelregisteret"
description: Implementasjonsguide for å overføre data om legemiddelbruk i institusjoner til Legemiddelregisteret
status: draft
version: 0.9.1
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
publisher:
  name: Folkehelseinstituttet (FHI)
  url: https://www.fhi.no
# dependencies:
# hl7.fhir.no.basis: 2.1.1
# hl7.fhir.no.basis: 2.2.0
# TODO #10 Sushi: error Structure Definition http://hl7.no/fhir/StructureDefinition/no-basis-Patient is missing a snapshot. Snapshot is required for import. (00:00.378 / 00:19.121, 21Mb)

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Informasjonsmodell: informasjonsmodell.html
  Artifacts: artifacts.html
  Oppgaver: oppgaver.html
  TOC: toc.html
