@startuml

skinparam Shadowing false

title "Eksempel på enkel flyt"
header "Legemiddeldata fra institusjon til Legemiddelregisteret"
footer "Folkehelseinstituttet"

actor Klient
boundary API
database  LMR

activate API
Klient -> API : Autentisere
API -> Klient : Autentisert (OK)

alt "Registrere Pasient"
Klient -> API : Søk på Pasient
API -> Klient : Returnér Pasient
else Hvis ikke
Klient -> API : Skriv Pasient
end

activate LMR
Klient -> API : Skriv Legemiddeladministrering
API -> LMR : Lagre Legemiddeladministrering
deactivate API
deactivate LMR

@enduml