@startuml

hide empty members
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

class Diagnose <<Condition>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Diagnose.html Diagnose _blank]]
class Episode <<Encounter>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Episode.html Episode _blank]]
class Helsepersonell <<Practitioner>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Helsepersonell.html Helsepersonell _blank]]
class Legemiddel <<Medication>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Legemiddel.html Legemiddel _blank]]
class Legemiddeladministrering <<MedicationAdministration>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Legemiddeladministrering.html Legemiddeladministrering _blank]]
class Legemiddelrekvirering <<MedicationRequest>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Legemiddelrekvirering.html Legemiddelrekvirering _blank]]
class Organisasjon <<Organization>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Organisasjon.html Organisasjon _blank]]
class Pasient <<Patient>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-Pasient.html Pasient _blank]]
class Substance [[https://hl7.org/fhir/R4/substance.html Substance _blank]]

Diagnose "1..1" --> Pasient : "subject"
Episode "0..1" --> Organisasjon : "serviceProvider"
Legemiddel "0..*" --> Substance : "ingredient.item"
Legemiddel "0..*" --> Legemiddel : "ingredient.item"
Legemiddeladministrering "1..1" --> Legemiddel : "medication"
Legemiddeladministrering "1..1" --> Pasient : "subject"
Legemiddeladministrering "0..1" --> Episode : "context"
Legemiddeladministrering "0..*" --> Diagnose : "reasonReference"
Legemiddeladministrering "0..1" --> Legemiddelrekvirering : "request"
Legemiddelrekvirering "1..1" --> Legemiddel : "medication"
Legemiddelrekvirering "1..1" --> Pasient : "subject"
Legemiddelrekvirering "0..1" --> Episode : "encounter"
Legemiddelrekvirering "1..1" --> Helsepersonell : "requester"
Legemiddelrekvirering "0..*" --> Diagnose : "reasonReference"
Legemiddelrekvirering "0..1" --> Legemiddelrekvirering : "priorPrescription"
Organisasjon "0..1" --> Organisasjon : "partOf"

@enduml