@startuml

hide empty members
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

class Diagnose <<Condition>>
class Episode <<Encounter>>
class Helsepersonell <<Practitioner>>
class Legemiddel <<Medication>>
class Legemiddeladministrering <<MedicationAdministration>>
class Legemiddelrekvirering <<MedicationRequest>>
class Organisasjon <<Organization>>
class Pasient <<Patient>>
class Substance

Diagnose "1..1" --> Pasient : "subject"
Episode "0..1" --> Organisasjon : "serviceProvider"
Legemiddel "0..*" --> Substance : "ingredient.item"
Legemiddel "0..*" --> Legemiddel : "ingredient.item"
Legemiddeladministrering "1..1" --> Legemiddel : "medication"
Legemiddeladministrering "1..1" --> Pasient : "subject"
Legemiddeladministrering "0..1" --> Episode : "context"
Legemiddeladministrering "0..*" --> Diagnose : "reasonReference"
Legemiddeladministrering "0..1" --> Legemiddelrekvirering : "request"
Legemiddelrekvirering "1..1" --> Legemiddel : "medication"
Legemiddelrekvirering "1..1" --> Pasient : "subject"
Legemiddelrekvirering "0..1" --> Episode : "encounter"
Legemiddelrekvirering "1..1" --> Helsepersonell : "requester"
Legemiddelrekvirering "0..*" --> Diagnose : "reasonReference"
Legemiddelrekvirering "0..1" --> Legemiddelrekvirering : "priorPrescription"
Organisasjon "0..1" --> Organisasjon : "partOf"

@enduml