@startuml

header "Legemiddeldata fra institusjon til Legemiddelregisteret"
title "Informasjonsmodell: UML klassediagam - MVP"
footer "Folkehelseinstituttet / Vali AS"

class Pasient <<Patient>> #lightgreen {
}

class Legemiddeladministrasjon <<MedicationAdministration>> #lightgreen {
}

Legemiddeladministrasjon --> Legemiddel 
Legemiddeladministrasjon --> Pasient
Legemiddeladministrasjon --> Helsepersonell
Legemiddeladministrasjon --> "Rolle helsepersonell"
Legemiddeladministrasjon --> Rekvisisjon
Legemiddeladministrasjon --> Institusjonsopphold

class Legemiddel <<Medication>> #lightgreen {
}

class Helsepersonell <<Practitioner>> {
}
class Organisasjon <<Organization>> #lightgreen {
}

Organisasjon --> Organisasjon

class Institusjonsopphold <<EpisodeOfCare>> #lightgreen {
}

Institusjonsopphold --> Pasient
Institusjonsopphold --> Organisasjon
Institusjonsopphold --> Diagnose

class Diagnose <<Condtition>> {
}

Diagnose ..> Pasient

class Rekvisisjon <<MedicationRequest>> {
}

Rekvisisjon --> Diagnose
Rekvisisjon --> Legemiddel
Rekvisisjon --> Pasient
Rekvisisjon --> Helsepersonell
Rekvisisjon --> Rekvisisjon

class "Rolle helsepersonell" <<PractitionerRole>> {
}



@enduml

