@startuml

header "Legemiddeldata fra institusjon til Legemiddelregisteret"
title "Informasjonsmodell: UML klassediagam - MVP"
footer "Folkehelseinstituttet / Vali AS"

class Pasient <<Patient>> #cyan {
}

class Legemiddeladministrasjon <<MedicationAdministration>> #cyan {
}

Legemiddeladministrasjon --> Legemiddel 
Legemiddeladministrasjon --> Pasient
Legemiddeladministrasjon --> Helsepersonell
Legemiddeladministrasjon --> Organisasjon
Legemiddeladministrasjon --> Rekvisisjon
Legemiddeladministrasjon --> Institusjonsopphold

class Legemiddel <<Medication>> #cyan {
}

class Helsepersonell <<Practitioner>> {
}
class Organisasjon <<Organization>> {
}

Organisasjon --> Organisasjon

class Institusjonsopphold <<EpisodeOfCare>> {
}

Institusjonsopphold --> Pasient
Institusjonsopphold --> Organisasjon
Institusjonsopphold --> Diagnose

class Diagnose <<Condtition>> {
}

Diagnose ..> Pasient

class Rekvisisjon <<MedicationRequest>> {
}

Rekvisisjon --> Diagnose
Rekvisisjon --> Legemiddel
Rekvisisjon --> Pasient
Rekvisisjon --> Helsepersonell
Rekvisisjon --> Rekvisisjon

@enduml

