@startuml

hide empty members
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

class Diagnose <<Condition>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-condition.html Diagnose _blank]] {
    clinicalStatus : CodeableConcept [0..1]
    code : CodeableConcept [1..1]
    identifier : Identifier [0..*]
    stage : BackboneElement [0..*]
    verificationStatus : CodeableConcept [0..1]
}
class Episode <<Encounter>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-encounter.html Episode _blank]] {
    class : Coding [1..1]
    identifier : Identifier [0..*]
    status : code [1..1]
}
class Legemiddel <<Medication>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-medication.html Legemiddel _blank]] {
    amount : Ratio [0..1]
    batch : BackboneElement [0..1]
    code : CodeableConcept [1..1]
    form : CodeableConcept [0..1]
    identifier : Identifier [0..*]
    ingredient : BackboneElement [0..*]
    status : code [0..1]
}
class Legemiddeladministrering <<MedicationAdministration>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-medicationadministration.html Legemiddeladministrering _blank]] {
    category : CodeableConcept [0..1]
    dosage : BackboneElement [0..1]
    effective[x] (sliced) : dateTime [1..1]
    effective[x] (effectiveDateTime) : dateTime [1..1]
    identifier : Identifier [0..*]
    instantiates : uri [0..*]
    reasonCode : CodeableConcept [0..*]
    status : code [1..1]
    statusReason : CodeableConcept [0..*]
}
class Legemiddelrekvirering <<MedicationRequest>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-medicationrequest.html Legemiddelrekvirering _blank]] {
    authoredOn : dateTime [0..1]
    category : CodeableConcept [0..*]
    courseOfTherapyType : CodeableConcept [0..1]
    doNotPerform : boolean [0..1]
    dosageInstruction : Dosage [0..*]
    groupIdentifier : Identifier [0..1]
    identifier : Identifier [0..*]
    instantiatesCanonical : canonical [0..*]
    instantiatesUri : uri [0..*]
    intent : code [1..1]
    priority : code [0..1]
    reasonCode : CodeableConcept [0..*]
    reported[x] : boolean [0..1]
    status : code [1..1]
    statusReason : CodeableConcept [0..1]
    substitution : BackboneElement [0..1]
}
class Organisasjon <<Organization>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-organization.html Organisasjon _blank]] {
    address : Address [0..*]
    alias : string [0..*]
    identifier (sliced) : Identifier [0..1]
    identifier (ENH) : Identifier [0..1]
    identifier (RESH) : Identifier [0..1]
    name : string [1..1]
    type : CodeableConcept [1..*]
}
class Pasient <<Patient>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-patient.html Pasient _blank]] {
    address : Address [0..*]
    birthDate : date [0..1]
    gender : code [0..1]
    identifier (sliced) : Identifier [0..1]
    identifier (FNR) : Identifier [0..1]
    identifier (DNR) : Identifier [0..1]
}
class Helsepersonell <<Practitioner>> [[https://hl7norway.github.io/LMDI/currentbuild/StructureDefinition-lmdi-practitioner.html Helsepersonell _blank]] {
    active : boolean [0..1]
    identifier : Identifier [1..1]
}
class Substance [[https://hl7.org/fhir/R4/substance.html Substance _blank]] {
    category : CodeableConcept [0..*]
    code : CodeableConcept [1..1]
    description : string [0..1]
    identifier : Identifier [0..*]
    ingredient : BackboneElement [0..*]
    instance : BackboneElement [0..*]
    status : code [0..1]
}

Diagnose "1..1" --> Pasient : "subject"
Episode "0..1" --> Organisasjon : "serviceProvider"
Legemiddel "0..*" --> Substance : "ingredient.item"
Legemiddel "0..*" --> Legemiddel : "ingredient.item"
Legemiddeladministrering "1..1" --> Legemiddel : "medication"
Legemiddeladministrering "1..1" --> Pasient : "subject"
Legemiddeladministrering "0..1" --> Episode : "context"
Legemiddeladministrering "0..*" --> Diagnose : "reasonReference"
Legemiddeladministrering "0..1" --> Legemiddelrekvirering : "request"
Legemiddelrekvirering "1..1" --> Legemiddel : "medication"
Legemiddelrekvirering "1..1" --> Pasient : "subject"
Legemiddelrekvirering "0..1" --> Episode : "encounter"
Legemiddelrekvirering "1..1" --> Helsepersonell : "requester"
Legemiddelrekvirering "0..*" --> Diagnose : "reasonReference"
Legemiddelrekvirering "0..1" --> Legemiddelrekvirering : "priorPrescription"
Organisasjon "0..1" --> Organisasjon : "partOf"
Substance "0..*" --> Substance : "ingredient.substance"

@enduml